name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target x86_64-unknown-linux-gnu --release
    - name: upload binary for x86_64-unknown-linux-gnu
      uses: actions/upload-artifact@v3.1.1
      with:
        name: jget-${GIT_SHA}-x86_64-unknown-linux-gnu
        path: target/x86_64-unknown-linux-gnu/jget

